# Generated by Django 2.0.3 on 2018-03-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID')),
                ('type', models.IntegerField(db_column='Type')),
                ('pwd', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
