# Generated by Django 2.0.3 on 2018-03-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.CharField(db_column='FID', max_length=20)),
                ('status', models.IntegerField(db_column='Status')),
                ('type', models.IntegerField(db_column='Type')),
                ('address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
    ]
